### ISSUE TITLE
A way to skip some files

### ISSUE THREAD

**Issue by ubenzer** [marc136/node-folder-hash#1]
A way to exclude some files from hash calculation would be helpful.

e.g. with multimatch: `hasher.hashElement(__dirname, {exclude: ["**/.*"]})`

## Possible Use Cases
1. To ignore system files such as `.DS_Store` to make them not effect folder hashes.
2. Depending on program logic, prevent a folder or o tree to affect parent folder hashes.

**Comment by marc136** [comment]
Hi @ubenzer,

I added exclude patterns in commit 09eb2eb, you can use it as you wrote above, additionally one can specify if the pattern should match only the file/folder name or its path  

To ignore .dotfiles, both options should work
```
var options = {
    excludes: ['.*'],
    match: { basename: true, path: false }
};
folderHash.hashElement(__dirname, options)
```
Or
```
var options = {
    excludes: ['**.*'],
    match: { basename: false, path: true }
};
folderHash.hashElement(__dirname, options)
```

If omitted, `match` defaults to `{ basename: true, path: true }`.

I did not use multimatch, but [minimatch](https://github.com/isaacs/minimatch) directly to combine multiple patterns into one RegEx.

**Comment by ubenzer** [comment]
Hi @marc136 ,
Many thanks for this useful library and for this feature! 👍 🍺 🍻
