### ISSUE TITLE
Ignore line endings option?

### ISSUE THREAD

**Issue by onionhammer** [marc136/node-folder-hash#107]
I use the hashes to determine whether to cachebust JSON files in a CDN, but the hashes are different depending on if I build on my dev machine (windows) vs the CI/CD server (linux). It would be great if I could get a consistent hashcode in both for troubleshooting.

**Comment by marc136** [comment]
I think a better solution would be to apply the same newline character sequence to the files with another tool, and then use this code to check for equality. That should be a lot faster.  
E.g. `sed` or `dos2unix` are [proposed in this stackoverflow question](https://askubuntu.com/a/803166).

If I were to add this option, I think I would need to switch from [efficiently reading the text files as a stream and dumping the chunks into the hash function](https://github.com/marc136/node-folder-hash/blob/0c7a47b96a1be7c7f5cc033eeba0873ee49bf282/index.js#L152) to reading the files line-by-line, which I presume to be a lot slower.

I'm open to be proven wrong, though.

**Comment by onionhammer** [comment]
@marc136 I would expect 99% of the overhead of this library is spent in file IO and the remaining on the 'crypto' libs hashing function; if implemented properly wouldn't the overhead be negligible?

Prior to

```js
        f.pipe(hash, { end: false });
```

you pipe to a different function that does the call to hash after it strips out line endings / whitespace (if the user specifies the option)
