### ISSUE TITLE
Node 6 support?

### ISSUE THREAD

**Issue by brianneisler** [marc136/node-folder-hash#12]
We just started using this module at https://serverless.com but immediately ran into an issue with the fact that the engine is set to 7 and above. This causes our node 6 builds to break. https://github.com/marc136/node-folder-hash/blob/master/package.json#L35
https://github.com/serverless/components/pull/344

It appears this issue dropped support for node 6 in addition to older versions of node
https://github.com/marc136/node-folder-hash/issues/2

was this intentional? Any reason not to support node 6 at the moment?

**Comment by marc136** [comment]
Hello @brianneisler,

It was not an intentional decision and node 6 is now supported with version 2.1.2.
After a small change, the tests pass on node 6, see https://circleci.com/gh/marc136/node-folder-hash/12

Regards,
marc

**Comment by marc136** [comment]
Hello @brianneisler, do you still need node 6? Or could I move this package to node 8 or the current LTS?
