### ISSUE TITLE
Add an option to ignore file names completely

### ISSUE THREAD

**Issue by analytik** [marc136/node-folder-hash#14]
Hi,

Thanks for this package. I'm not sure if this aligns with your design goals for it, but for my use case, I just want to create hashes from file contents and nothing else. I.e.

- two files with different names or paths, but same content will have the same hash
- renaming or moving a file won't change its hash
- I am not looking for folder hashes at all so I don't have an opinion on what hash should that produce, although I think renaming a file should change the folder hash, even if no file hashes would be changed.

Regarding the code, the option could be called hashByContentOnly, and the only code change I can think of is in hashFilePromise function changing to this block slightly:

```        return new Promise((resolve, reject) => {
            try {
                const hash = crypto.createHash(options.algo);
                if (options.files.hashByContentOnly || (isRootElement && options.files.ignoreRootName)) {
                    log.match(`omitted name of ${filePath} from hash`)
                } else {
                    hash.write(name);
                }
```

**Comment by analytik** [comment]
Or maybe a cleaner solutions - provide two hashes, one for file contents only, and one for name+contents (currently logic). This would need to propagate, so that parent folders could also calculate hashes with and without names included. Thoughts?

**Comment by marc136** [comment]
Hello @analytik,
than you for the suggestion.

For your use case you already could use this package similar to this code
```
const options = { files: { ignoreRootName: true } };
fs.readdir(folder, (err, files) => {
    files.map(basename => hashElement(basename, folder, options)
        .then(console.log));
});
```
(see also the added test in commit 8e25f5ff16b18d421c64864d8d9e0a5aec76ac43)

But this is not nice and I would like to support it better. I think I will add the option `ignoreBasename` to both `options.files` and `options.folders` either tomorrow or over the weekend.
