### ISSUE TITLE
Drop support for node.js 0.12

### ISSUE THREAD

**Issue by marc136** [marc136/node-folder-hash#2]
No need to support [versions below node 4.0](https://github.com/nodejs/LTS#lts-schedule)

**Comment by marc136** [comment]
Solved in 384f0f0

**Comment by brianneisler** [comment]
This commit dropped support for node 6 as well. Was that intentional?

**Comment by marc136** [comment]
I'm not sure why I picked node 7 as engine, I think it was because of an dependency.
The examples behave fine when using 6.0.0 so I'll reduce the necessary version to 6.
