### ISSUE TITLE
Asynchronous hashing

### ISSUE THREAD

**Issue by aabuhijleh** [marc136/node-folder-hash#24]
Hashing is done via Node's `crypto` module which [executes in the main thread](https://github.com/nodejs/node/issues/678). I'm using this module in an Electron app and hashing a large folder causes the app to take a heavy performance hit.

**Comment by marc136** [comment]
I would propose that you use one or multiple worker threads to mitigate this in your electron app.
Thanks for linking this issue, maybe something will happen there.

So far I do not plan to add any cluster-like features to this library. If you find a nice solution, I would look at integrating it.
But I would expect generating the hashes over several subfolders in different threads to provide better results (depending on the use case).

**Comment by jorangreef** [comment]
@marc136 you could look into using https://github.com/ronomon/crypto-async to do your hashing. It uses the threadpool to give you pure asynchronous crypto functions without the overhead and complexity of cluster-like features. It won't block the main thread, plus you get multi-core hashing throughput.
