### ISSUE TITLE
command line `folder-hash scr` command

### ISSUE THREAD

**Issue by dnim** [marc136/node-folder-hash#32]
Hi! Is it possible to have command line _folder-hash scr_ command to use it for checking folders for changes during CI/CD?

**Comment by marc136** [comment]
I currently do not have a cli, but it should be quite simple to implement for your own use case.

But you would also need a script to compare the changes to the last run, I guess simply piping to diff would not suffice.
So I think it would be easier to write a script that imports folder-hash, creates the new hash structure and then compare it directly (and e.g. push the changes to a file server or artifact store).

But I will think about adding a cli option, right now I am not sure how to implement the possible options in a general way yet, simplest (for me) would be to load a config file.

Regards,
marc

**Comment by marc136** [comment]
Hello @dnim,

I added a simple command line interface with v3.3.0 and forgot to merge it to master, see also PR #38 

Example usage:
```
npx folder-hash --help
```

You can pass the configuration object of the normal JS API as a json file.

Cheers,
marc
