### ISSUE TITLE
Flag to skip missing symlinks

### ISSUE THREAD

**Issue by cadorn** [marc136/node-folder-hash#41]
If I have a symlink that points to a path that does not exist it will currently throw.

I need a flag to ignore these *errors* and have the hashing continue.

In this case, skip trying to hash the targeted content of the symlink and just hash the name of the symlink as well as the target path. This will then generate a new hash whenever the symlink is renamed or pointed to a different path.

**Comment by marc136** [comment]
I know that this is an old issue @cadorn, but can you give me an example of the error that you received?
On my system I only saw `ENOENT` when trying to hash a symbolic link where the target was not existing. 
You can see my take in 59853aefd6 it in the [fix_#41 branch](https://github.com/marc136/node-folder-hash/tree/fix_%2341).

**Comment by marc136** [comment]
I realized that I misunderstood the requirements. I am working on a more general solution

**Comment by marc136** [comment]
I added a solution that not only adds this behavior, but also allows general settings for soft links, like always also hashing the target path or to skip them completely.
https://github.com/marc136/node-folder-hash/blob/symbolic-links/test/symbolic-links.js

**Comment by cadorn** [comment]
Very nice!

IIRC there was another issue that caused us to have to swap out this lib. I'll see what it was so you can harden it even more.

**Comment by marc136** [comment]
Thanks, that sounds great.
Do you also recall why you had symlinks that could not be accessed? Was it a permission issue or actually to-remove-links?

**Comment by cadorn** [comment]
> Do you also recall why you had symlinks that could not be accessed? Was it a permission issue or actually forgotten links?

We have cases where we have relative symlinks that do not resolve until they are copied to a new location. But we need to hash them before copying. So for a symlink with value `./foo` we need the `hash('./foo')` do detect if any symlinks have changed.

**Comment by marc136** [comment]
Ok, thank you.

**Comment by cadorn** [comment]
Just to follow up on the symlink issue which I presume is fixed now. Will try soon.

This is the patch we are currently running on top of https://github.com/marc136/node-folder-hash/blob/02398bb0712b301df10e65054b6c83a61ea635f8/index.js

![Screen Shot 2020-06-18 at 10 56 01 AM](https://user-images.githubusercontent.com/18679/85055818-0905d300-b153-11ea-8106-3cebc0e41404.png)

**Comment by cadorn** [comment]
The new `symbolicLinks.hashTargetPath` option is documented as:  **Set to true to add the resolved link target to the hash (uses fs.readlink)**

The word **resolved** is throwing me off. It implies that the link target is run through `realpath` which does not seem to be the case in the code.

Should it not be something like?: **Set to true to add the link target to the hash (uses fs.readlink)**

**Comment by cadorn** [comment]
Also, the `follow` property values seem a bit overloaded.
Maybe:
```
{
    "include": true,   // true, false
    "follow": true    // true, false
}
```

**Comment by cadorn** [comment]
The other issue seems to have been with a different library.

We are now running the latest changes you made. Will report back if there are any other issues. Will take a week or so to test all use-cases.

**Comment by marc136** [comment]
> Just to follow up on the symlink issue which I presume is fixed now. Will try soon.
> 
> This is the patch we are currently running on top of https://github.com/marc136/node-folder-hash/blob/02398bb0712b301df10e65054b6c83a61ea635f8/index.js
> 
> ![Screen Shot 2020-06-18 at 10 56 01 AM](https://user-images.githubusercontent.com/18679/85055818-0905d300-b153-11ea-8106-3cebc0e41404.png)

After the upgrade to node 10.10, I use [lstat for the first level](https://github.com/marc136/node-folder-hash/blob/333c348215be93308d25568cd67e6937ff8915e9/index.js#L54) and for the subsequent ones I rely on [the Dirent values returned by readdir](https://github.com/marc136/node-folder-hash/blob/333c348215be93308d25568cd67e6937ff8915e9/index.js#L108) so I think that this change is already incorporated.

**Comment by marc136** [comment]
> Also, the `follow` property values seem a bit overloaded.
> Maybe:
> ```
> {
>     "include": true,   // true, false
>     "follow": true    // true, false
> }
> ```

Hmm, good point. It made sense to me from the implementation point of view.
But I also see your point and would try to simplify the choices. Also, the names do not fit well to the existing API design.

---

I would like to be able to configure the following behaviors:
- skip: The link should not be listed in the results at all
- hash over basename
- hash over basename and target path
- hash over basename and content (behavior of 3.2.3, should be default in 4.0)
- hash over basename, target path and content
- hash over target path and content
- hash over content
And I would like to be able to ignore errors while trying to hash the content

---
So maybe defaults like this make sense and uses more similar wording to the other options:

```js
{
  include: true,
  ignoreBasename: false,
  ignoreTargetPath: true,
  ignoreTargetContent: false,
  ignoreTargetContentAfterError: false,
}
```

And I guess for your use case you would then need to supply
```js
{ ignoreTargetPath: false, ignoreTargetContent: true }
```

**Comment by cadorn** [comment]
> So maybe defaults like this make sense and uses more similar wording to the other options:

Much better. :)

**Comment by marc136** [comment]
I pushed the API change now. The tests all pass so I think you could try it.

**Comment by cadorn** [comment]
I have updated our code with latest changes. Will let you know if we run into any issues.

**Comment by cadorn** [comment]
Have not heard back about any regressions so it appears to be working properly.
