### ISSUE TITLE
Documentation for migrating from version 2 to 3?

### ISSUE THREAD

**Issue by cvoege** [marc136/node-folder-hash#43]
Were there breaking changes in version 3? Are they documented anywhere?

**Comment by marc136** [comment]
Yes, I wrote about it in [the wiki](https://github.com/marc136/node-folder-hash/wiki/Versions-(breaking-changes-and-migration-information)#breaking-changes-in-300).
Major change was that all entries are sorted to have the same order on Linux and Windows.

**Comment by cvoege** [comment]
Gotcha, might be a good idea to add that to tags for "Releases", as that's where I usually go to understand package updates.

**Comment by marc136** [comment]
Good idea, I changed the 3.0.0 tag
