### ISSUE TITLE
Add an 'includes' option

### ISSUE THREAD

**Issue by ColoradoNate** [marc136/node-folder-hash#7]
It'd be nice to have an 'includes' option that allows one to specify what files to include.  In other words, perhaps I only want to hash all *.js files, and don't know and don't care about any other files.

**Comment by dternyak** [comment]
Hello!

I just wanted to chime in and mention that an `includes` option would be valuable for me as well!

Thanks a lot for making such a nice utility @marc136! :) I see you've assigned this issue to yourself already. Is work to integrate this already underway? If not, would you like any assistance?

Thanks again!

**Comment by marc136** [comment]
Hello @ColoradoNate and @dternyak, 

I started on the include option and realized that I made a mistake in naming the options and will need to introduce a major version change.

The exclude and include patterns are currently matched to both the folders and the files.
If I only want to include *.js* files, I would need to also write a special includes rule that would apply to all folders I want to check for these *.js* files. This would be very error-prone.

For the next version, I will change the option format to (most likely) this one:
```
{
    algo: 'sha1',
    encoding: 'base64',
    match : {
        folders: {
            exclude: [],
            include: [],
            matchOnlyBasename: false
        },
        files: {
            exclude: [],
            include: [],
            matchOnlyBasename: false
        }
    }
}
```

This allows for different rules for folders and files, and I also want to add a flag to limit the pattern matching to the basename (without the full path).
You can check out the progress in the [dev branch](/marc136/node-folder-hash/tree/dev). Currently I am reworking the tests and will then add the new options configuration.

Regards,
marc

**Comment by marc136** [comment]
Hello @ColoradoNate  and @dternyak,

I added an include flag in ef804a8, it can be used e.g. like that:
```js
const { hashElement } = require('folder-hash');

const options = {
    folders: { exclude: ['.*', 'node_modules', 'test_coverage'] },
    files: { include: ['*.js', '*.json'] }
};

console.log('Creating a hash over the current folder:');
hashElement('.', options)
    .then(hash => {
        console.log(hash.toString());
    })
    .catch(error => {
        return console.error('hashing failed:', error);
    });
```
Default options:
```js
{
    algo: 'sha1',       // see crypto.getHashes() for options
    encoding: 'base64', // 'base64', 'hex' or 'binary'
    files: {
        exclude: [],
        include: [],
        matchBasename: true,
        matchPath: false
    },
    folders: {
        exclude: [],
        include: [],
        matchBasename: true,
        matchPath: false
    }
}
```
