### ISSUE TITLE
Allow fs to be passed in

### ISSUE THREAD

**Issue by masaeedu** [marc136/node-folder-hash#8]
This would be useful in testing where a dummy filesystem like https://www.npmjs.com/package/memfs is used.

**Comment by masaeedu** [comment]
Note, this would also help with testing the module itself: memfs provides a convenient way to populate a virtual filesystem with folders and files using a plain-old JS object. This would obviate the need for `test/helper/helper.js`.

**Comment by marc136** [comment]
I like the idea to simplify testing, I'll look into memfs next week.
