### ISSUE TITLE
Folder hashes not identical for Windows and Unix 

### ISSUE THREAD

**Issue by vladitasev** [marc136/node-folder-hash#90]
Hello,

Thank you for developing and maintaining this project!

There seems to be an issue with getting the same directory's hash on Windows and Unix. The individual files' hashes are identical, however the files are not ordered in the same way on Unix and Windows inside the directory (small vs caps ordering is different). Therefore one obtains a different hash for the exact same directory depending on the OS.

I checked the source code and I saw you have:
```
const children = files.sort()
```
on line 112, probably to address exactly this. However, since `files` is not an array of strings, but of objects, it seems that it never gets rearranged.

I think it needs to be:

```
const children = files.sort((a, b) => {
  if (a.name > b.name) {
    return 1;
  }
  etc...
});
```

Could you please look into it?

Regards,
Vladislav

**Comment by marc136** [comment]
Thanks @vladitasev, I broke this by accident with commit b2c9fc6
